root: true

extends:
    - 'eslint:recommended'
    - 'plugin:vue/vue3-recommended'
    - 'plugin:prettier/recommended'
    - 'plugin:@typescript-eslint/recommended'

env:
    node: true

parser: 'vue-eslint-parser'
parserOptions:
    parser: '@typescript-eslint/parser'
    ecmaVersion: 12
    'sourceType': 'module'
    tsConfigRootDir: __dirname

plugins:
    - vue
    - '@typescript-eslint'

rules:
    vue/multi-word-component-names: off
