version: 0.2

env:
    variables:
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

phases:
    install:
        runtime-versions:
            nodejs: latest
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase...
    build:
        commands:
            - echo Build started on `date`
            - npm install
            - npm run build:prod
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files: build/*
    name: fsufitch-homepage-artifact
    # discard-paths: yes
