version: 0.2

env:
    variables:
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

phases:
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo Installing build dependencies...
            - apt-get update
            - apt-get install -y protobuf-compiler

    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase...
    build:
        commands:
            - echo Build started on `date`
            - npm install
            - npm run build:prod

    post_build:
        commands:
            - echo Creating Cloudfront invalidation
            - aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION} --invalidation-batch
              'Paths={Quantity=1,Items=[/*]},CallerReference=codebuild-'$(date +%s)
            - echo Build completed on `date`
artifacts:
    files: '**/*'
    name: fsufitch-homepage-artifact
