baseURL = "https://filip.sufitchi.name/"

theme = "LoveIt"

title = "Filip's Corner"
languageCode = "en"

enableRobotsTXT = true
enableGitInfo = true

enableEmoji = true

[pagination]
  pagerSize = 10

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "resume"
    name = "Resumé"
    url = "https://docs.google.com/document/d/16zpkvHbJF9cVp5u56MnsDBIVBk-Fuk6riZLXBhrElnc/edit?usp=sharing"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/blog/"
    weight = 4
  # [[menu.main]]
  #   identifier = "tags"
  #   name = "Tags"
  #   url = "/tags/"
  #   weight = 9

[markup]
  [markup.highlight]
    noClasses = false  # required by LoveIt’s CSS pipeline

  [markup.goldmark.parser]
  autoHeadingIDType = "github-ascii"

  [markup.goldmark.renderer]
    unsafe = true  # allow raw HTML in markdown

  [markup.goldmark.extensions]
  typographer = true
  strikethrough = false  # strikethrough is broken by subscript, see: https://github.com/gohugoio/hugoDocs/commit/6467bda931c329e3ccbdcf222d031c18c38b967c
  
  [markup.goldmark.extensions.extras.delete]
  enable = true

  [markup.goldmark.extensions.extras.insert]
  enable = true

  [markup.goldmark.extensions.extras.mark]
  enable = true

  [markup.goldmark.extensions.extras.subscript]
  enable = true

  [markup.goldmark.extensions.extras.superscript]
  enable = true

[params]
  defaultTheme = "auto"
  title = "Filip's Corner"

  [params.app]
    title = "Filip's Corner"
    svgFavIcon = "/favicon.svg"

  [params.header.title]
    name = "Filip's Corner"

  [params.search]
    enable = true
    type = "lunr"

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.jpg"
      title = "Filip Sufitchi"
      subtitle = "Software Engineer • Maker • Nerd"
      typeit = true
      social = true

  [params.social]
    GitHub = "fsufitch"
    Medium = "fsufitch"
    Linkedin = "fsufitch"
    # Email = "[email protected]"
    RSS = true

  [params.page]
    author = "Filip Sufitchi"
    authorLink = "/about/"
    lightgallery = true

    [params.page.toc]
      enable = false

    [params.page.share]
      enable = true

  [params.typeit]
    enable = true
    speed = 50
